---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: open5gs-mongodb-pvc
  labels:
    app: open5gs-mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
