---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-mongodb
  labels:
    name: open5gs-mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: open5gs-mongodb
