---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nrf
  labels:
    epc-mode: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nrf
  template:
    metadata:
      labels:
        epc-mode: nrf
    spec:   
      containers:
        - name: nrf
          image: boeboe/open5gs:v2.2.0          
          command: ["open5gs-nrfd", "-c", "/open5gs/config-map/nrf.yaml"]
          volumeMounts:
            - name: open5gs-nrf-config
              mountPath: /open5gs/config-map/nrf.yaml
              subPath: "nrf.yaml"
      serviceAccountName: open5gs-nrf-sa
      volumes:
        - name: open5gs-nrf-config
          configMap:
            name: open5gs-nrf-config
