---
apiVersion: v1
kind: Service
metadata:
  labels:
    epc-mode: open5gs-webui
  name: open5gs-webui
spec:
  ports:
  - name: http-open5gs-webui
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    epc-mode: webui
