---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-sgwu-config
  labels:
    epc-mode: sgwu
data:
  sgwu.yaml: |
    logger:
        file: /var/log/open5gs/sgwu.log

    parameter:
        no_ipv6: true

    sgwu:
        gtpu:
           dev: eth0
        pfcp:
           dev: eth0
