---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-mme-config
  labels:
    epc-mode: mme
data:
  mme.yaml: |
    logger:
        file: /var/log/open5gs/mme.log
    
    parameter:
    
    mme:
        freeDiameter: /open5gs/config-map/diameter-mme.conf
        s1ap:
           dev: eth0        
        gtpc:
           dev: eth0        
        gummei:
          plmn_id:
            mcc: 208
            mnc: 93
          mme_gid: 2
          mme_code: 1
        tai:
          plmn_id:
            mcc: 208
            mnc: 93
          tac: 12345
        security:
            integrity_order : [ EIA1, EIA2, EIA0 ]
            ciphering_order : [ EEA0, EEA1, EEA2 ]
        network_name:
            full: Open5GS
    
    sgw:
        gtpc:
          - name: "open5gs-sgwc"
    
    smf:
        gtpc:
          - name: "open5gs-smf"
