---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-mme
  labels:
    epc-mode: mme
spec:
  ports:
#  - name: s1ap
#    port: 36412
#    protocol: SCTP
#    nodePort: 36412
  - name: s6a
    port: 3868
    protocol: TCP
  selector:
    epc-mode: mme
