---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-smf
  labels:
    epc-mode: smf
spec:
  clusterIP: None
#  ports:
#  - name: gx
#    port: 3868
#    protocol: TCP  
#  - name: pfcp
#    port: 3868
#    protocol: UDP
  selector:  
    epc-mode: smf
