---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config
  labels:
    epc-mode: upf
data:
  upf.yaml: |
    logger:
        file: /var/log/open5gs/upf.log

    upf:
        pfcp:
           dev: eth0
        gtpu:
           dev: eth0
        pdn:
          - addr: 10.45.0.1/16
            apn: internet
        dns:
          - 8.8.8.8
          - 8.8.4.4
