---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: open5gs-upf
  labels:
    epc-mode: upf
spec:
  replicas: 1
  serviceName: "open5gs-upf"
  selector:
    matchLabels:
      epc-mode: upf
  template:
    metadata:          
      labels:
        epc-mode: upf
    spec:
      containers:
        - name: upf
          image: boeboe/open5gs:v2.2.0
          securityContext:
            privileged: true
            #sysctls:
            #- name: net.ipv6.conf.all.disable_ipv6
            #  value: 0
            capabilities:
              add: ["NET_ADMIN"]
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - ip tuntap add name ogstun mode tun;
              ip addr add 10.45.0.1/16 dev ogstun;
              sysctl -w net.ipv6.conf.all.disable_ipv6=0;
              ip addr add cafe::1/64 dev ogstun;
              ip link set ogstun up;
              sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward";
              iptables -t nat -A POSTROUTING -s 10.45.0.0/16 ! -o ogstun -j MASQUERADE;
              open5gs-upfd -c /open5gs/config-map/upf.yaml;
          volumeMounts:
          - name: open5gs-upf-config
            mountPath: /open5gs/config-map/upf.yaml
            subPath: "upf.yaml"
          - mountPath: /dev/net/tun
            name: dev-net-tun
      serviceAccountName: open5gs-upf-sa
      volumes:
        - name: open5gs-upf-config
          configMap:
            name: open5gs-upf-config            
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
